services:
  app:
    build:
      context: .
      secrets: 
        - ghapikey
    ports:
      - '3001:3000'
    read_only: true
    volumes:
      - '../../configs/task-queue-service:/sandbox'
      # - './static:/app/static'
    environment: 
      db__host: task-queue-service-db
      db__username: task-queue-service
      db__password: task-queue-service
      db__database: task-queue-service
    depends_on:
      task-queue-service-db:
        condition: service_healthy
    links:
      - task-queue-service-db

  task-queue-service-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: task-queue-service
      POSTGRES_USER: task-queue-service
      POSTGRES_PASSWORD: task-queue-service
    ports: ["5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -h task-queue-service-db -U task-queue-service"]
      interval: 2s
      timeout: 5s
      retries: 20

secrets:
  ghapikey:
    environment: GH_API_KEY